FROM httpd:2.4

LABEL version="0.99" \
	  author="Francisco Fregona" \
	  maintainer="franciscofregona@gmail.com" \
	  info="Simple web server to show files on /srv"

EXPOSE 80

VOLUME /usr/local/apache2/htdocs/