# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

diskSize = 1    #Size in Gigabytes (2 per server, so times 4 consumption)
ramSize = 512   #Memory for the VMs (2 servers, so times 2 consumption)
cpuCount = 1    #No. of CPUs for the VMs (again... 2 servers...)

Vagrant.configure(2) do |config|

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

 config.vm.define "nfsServer1", primary: true do |nfsServer1|

    nfsServer1.vm.box = "debian/stretch64"
    # nfsServer1.vm.box_check_update = false

    nfsServer1.vm.hostname = "nfsServer1"
    #nfsServer1.vm.boot_timeout = 3600


    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    ## ==Puerto para sftp==
    # nfsServer1.vm.network "forwarded_port", guest: 69, host: 6969
    ## ==Puerto para ssh==
    nfsServer1.vm.network "forwarded_port", guest: 22, host: 2221, id: "ssh"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    #nfsServer1.vm.network "private_network", ip: "192.168.33.20", virtualbox__intnet: "mynetwork"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical nfsServer1.ce on
    # your network.
    # nfsServer1.vm.network "public_network"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # nfsServer1.vm.synced_folder "../data", "/vagrant_data"
    # nfsServer1.vm.synced_folder "../../Recursos/Isos/us1804", "/iso", create: true
    
    nfsServer1.ssh.forward_agent = true
    nfsServer1.ssh.port=2221

    # nfsServer1.vm.provision "ansible" do |ansible|
    #   ansible.inventory_path = "../../inventory/vagrant/hosts.yml"
    #   ansible.playbook = "../../playbooks/provisionnfsServer1.yml"
    #   ansible.limit = "vagrantnfsServer1"
    #   ansible.config_file = "../../ansible.cfg"
    # end #provision
    
    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    nfsServer1.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
       # Customize the amount of memory on the VM:
      vb.memory = ramSize
      vb.cpus = cpuCount
     
      #Extra disks
      # diskSize = 1 #Size in Gigabytes
      #Make room for a 3rd disk
      vb.customize [ "storagectl", :id, "--name", "SATA Controller","--portcount", "3"]

      disk1file = "disk1server1.vmdk"
      disk2file = "disk2server1.vmdk"
      unless File.exist?(disk1file) then
        vb.customize [ "createmedium", "disk", "--filename", "disk1server1.vmdk", "--format", "vmdk", "--size", 1024 * diskSize ]
      end
      unless File.exist?(disk2file) then
        vb.customize [ "createmedium", "disk", "--filename", "disk2server1.vmdk", "--format", "vmdk", "--size", 1024 * diskSize ]
      end
      vb.customize [ "storageattach", :id , "--storagectl", "SATA Controller", "--port", "1", "--device", "0", "--type", "hdd", "--medium", disk1file]
      vb.customize [ "storageattach", :id , "--storagectl", "SATA Controller", "--port", "2", "--device", "0", "--type", "hdd", "--medium", disk2file]
    end #virtualbox
  end #nfsServer1

  config.vm.define "nfsServer2", primary: true do |nfsServer2|

    nfsServer2.vm.box = "debian/stretch64"
    # nfsServer2.vm.box_check_update = false

    nfsServer2.vm.hostname = "nfsServer2"
    #nfsServer2.vm.boot_timeout = 3600


    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    ## ==Puerto para sftp==
    # nfsServer2.vm.network "forwarded_port", guest: 69, host: 6969
    ## ==Puerto para ssh==
    nfsServer2.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    #nfsServer2.vm.network "private_network", ip: "192.168.33.20", virtualbox__intnet: "mynetwork"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical nfsServer2.ce on
    # your network.
    # nfsServer2.vm.network "public_network"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # nfsServer2.vm.synced_folder "../data", "/vagrant_data"
    # nfsServer2.vm.synced_folder "../../Recursos/Isos/us1804", "/iso", create: true
    
    nfsServer2.ssh.forward_agent = true
    nfsServer2.ssh.port=2222

    # nfsServer2.vm.provision "ansible" do |ansible|
    #   ansible.inventory_path = "../../inventory/vagrant/hosts.yml"
    #   ansible.playbook = "../../playbooks/provisionnfsServer2.yml"
    #   ansible.limit = "vagrantnfsServer2"
    #   ansible.config_file = "../../ansible.cfg"
    # end #provision
    
    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    nfsServer2.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
       # Customize the amount of memory on the VM:
      vb.memory = ramSize
      vb.cpus = cpuCount
     
      #Extra disks
      # diskSize = 1 #Size in Gigabytes
      #Make room for a 3rd disk
      vb.customize [ "storagectl", :id, "--name", "SATA Controller","--portcount", "3"]

      disk1file = "disk1server2.vmdk"
      disk2file = "disk2server2.vmdk"
      unless File.exist?(disk1file) then
        vb.customize [ "createmedium", "disk", "--filename", "disk1server2.vmdk", "--format", "vmdk", "--size", 1024 * diskSize ]
      end
      unless File.exist?(disk2file) then
        vb.customize [ "createmedium", "disk", "--filename", "disk2server2.vmdk", "--format", "vmdk", "--size", 1024 * diskSize ]
      end
      vb.customize [ "storageattach", :id , "--storagectl", "SATA Controller", "--port", "1", "--device", "0", "--type", "hdd", "--medium", disk1file]
      vb.customize [ "storageattach", :id , "--storagectl", "SATA Controller", "--port", "2", "--device", "0", "--type", "hdd", "--medium", disk2file]
    end #virtualbox
  end #nfsServer2

end #config
