# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

 config.vm.define "homeServer", primary: true do |homeServer|

    homeServer.vm.box = "debian/stretch64"
    # homeServer.vm.box_check_update = false

    homeServer.vm.hostname = "homeServer"
    #homeServer.vm.boot_timeout = 3600


    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    ## ==Puerto para sftp==
    # homeServer.vm.network "forwarded_port", guest: 69, host: 6969
    ## ==Puerto para ssh==
    homeServer.vm.network "forwarded_port", guest: 22, host: 2220, id: "ssh"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    #homeServer.vm.network "private_network", ip: "192.168.33.20", virtualbox__intnet: "mynetwork"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical homeServer.ce on
    # your network.
    # homeServer.vm.network "public_network"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # homeServer.vm.synced_folder "../data", "/vagrant_data"
    # homeServer.vm.synced_folder "../../Recursos/Isos/us1804", "/iso", create: true
    
    homeServer.ssh.forward_agent = true
    homeServer.ssh.port=2220

    homeServer.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "../../inventory/vagrant/hosts.yml"
      ansible.playbook = "../../playbooks/provisionHomeServer.yml"
      ansible.limit = "vagrantHomeServer"
      ansible.config_file = "../../ansible.cfg"
    end #provision
    
    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    homeServer.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
       # Customize the amount of memory on the VM:
      vb.memory = "512"
    end #virtualbox
  end #server
end #config
