---

software_raid_alerts_email: "email@example.com"
software_raid_create_kwargs: "--run" # force the creation if there are any prompts
software_raid_devices:
- device: /dev/md0
  level: 0
  components:
    - /dev/sdb
    - /dev/sdc
  # filesystem_type: "ext4"
  mount_point: "/srv/data"
  mount_options: "noatime,noexec,nodiratime,noauto"
  dump: 0
  passno: 0
# - device: /dev/md1
#   level: 1
#   components:
#     - /dev/sdb
#     - /dev/sdc