---
# tasks file for virtualbox
- name: Install VirtualBox. Prereq. Install apt-transport-https
  apt:
    name: ['apt-transport-https']
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' and  "ansible_distribution_version" >= "9"
  tags:
    - prereq
    - virtualbox

# Tested: this is necesary, the home server actually needs it too.
- name: Install VirtualBox. Prereq. Install kernel files.
  apt:
    name: ['linux-headers-amd64', 'linux-headers-4.9.0-8-amd64', 'gcc','build-essential','perl']
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' and  "ansible_distribution_version" >= "9"
  tags:
    - prereq
    - virtualbox

- name: Install VirtualBox. Encryption keys for repository.
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - "http://www.virtualbox.org/download/oracle_vbox_2016.asc"
    # - "http://www.virtualbox.org/download/oracle_vbox.asc"
  when: ansible_distribution == 'Debian' and  "ansible_distribution_version" >= "9"
  tags: virtualbox

- name: Install VirtualBox. Adding repository.
  apt_repository:
    repo: deb http://download.virtualbox.org/virtualbox/debian stretch contrib
    state: present
  when: ansible_distribution == 'Debian' and  "ansible_distribution_version" >= "9"
  tags: virtualbox

- name: Install VirtualBox. Actual install.
  apt:
    name: ['virtualbox-5.2'] 
    state: present
    allow_unauthenticated: yes
    update_cache: yes
    install_recommends: no
  when: ansible_distribution == 'Debian' and  "ansible_distribution_version" >= "9"
  tags: virtualbox

# TODO: Test if this is necesary only on my vagrant test setup or the home server actually needs it too.
- name: Install Virtualbox. Recompile vbox kernel module
  shell: /sbin/vboxconfig
  when: ansible_distribution == 'Debian' and  "ansible_distribution_version" >= "9" # and "ansible_virtualization_type" = "virtualbox"
  tags: virtualbox
