---
# tasks file for goss

- name: Goss. Copy the deb installer over.
  copy:
    src: ../resources/binaries/goss
    dest: /usr/local/bin/goss
    owner: root
    group: root
    mode: u+rx
  tags: goss

- name: Goss. Copy goss.yaml file to the host
  template:
    src: "{{inventory_dir}}/group_files/{{goss_template}}"
    dest: /etc/mygoss.yaml
  tags: goss

#This task is not tagged, as we want it to run from provisioning.
#If we want to run tests manually, there's no need for it.
- name: Goss. Pause for 20 seconds to wait for HA.
  pause:
    seconds: 25
    prompt: "Waiting for the HA service to pop up. Otherwise the tests will fail."

- name: Goss. Run the tests
  goss:
    path: /etc/mygoss.yaml
  tags: goss
