---
# tasks file for goss

- name: Goss. Copy the deb installer over.
  copy:
    src: ../resources/binaries/goss
    dest: /usr/local/bin/goss
    owner: root
    group: root
    mode: u+rx
  tags: goss

- name: Goss. Copy goss.yaml file to the host
  template:
    src: "{{inventory_dir}}/group_files/{{goss_template}}"
    dest: /etc/mygoss.yaml
  tags: goss

- name: Goss. Run the tests
  goss:
    path: /etc/mygoss.yaml
  tags: goss
