---
# tasks file for docker
- name: Docker.  Prereqs.
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    state: present
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' and  "ansible_distribution_version" >= "9"
  # when: ansible_virtualization_role == "guest" and ansible_virtualization_type == "virtualbox"
  tags:
    - prereq
    - docker

- name: Docker. Add repo key.
  apt_key:
    state: present
    url: "{{docker_repo_key_url}}"
  tags: docker

# # TODO: check the repo key against its fingerprint
# # according to https://docs.docker.com/install/linux/docker-ce/debian/#set-up-the-repository
# sudo apt-key fingerprint 0EBFCD88

# pub   4096R/0EBFCD88 2017-02-22
#       Key fingerprint = 9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88
# uid                  Docker Release (CE deb) <docker@docker.com>
# sub   4096R/F273FCD8 2017-02-22

- name: Docker. Add the Docker repo
  apt_repository:
    repo: "{{docker_apt_repo_url}}"
    state: present
  tags: docker

- name: Docker. Install Docker. Actual Install
  apt:
    name: ['docker-ce']
    update_cache: yes
    state: present
    # install_recommends: no 
  tags: docker

- name: Docker. Install Docker bindings for Python (ansible module dependence)
  pip:
    name: docker
  tags: docker
  
- name: Docker. Copy the dockerfile for the service. Unused
  copy:
    src: Dockerfile
    dest: /srv/Dockerfile
  tags: docker

# Equivalent docker command would have been something along the lines of
# docker build -t simplewebserver:0.99 /srv
- name: Docker. Make an image with that dockerfile
  docker_image:
    path: /srv/
    name: simplewebserver
    state: present
    tag: 0.99
    # buildargs:
    #   listen_port: 8080
    #   log_volume: /var/log/myapp
  tags: docker

# Equivalent docker command will be
# docker run -d  -p 8080:80 --restart always -v /mnt:/usr/local/apache2/htdocs simplewebserver:0.99
- name: Docker. Run the container for the webserver
  docker_container:
    name: "{{container_name}}"
    image: simplewebserver:0.99
    volumes:
      - /mnt:/usr/local/apache2/htdocs/:ro
    state: started
    restart: yes
    restart_policy: always
    ports:
     - "8080:80"  #TODO: Check order of ports
  tags: docker


