---
# tasks file for hosts
- name: HOSTS. Ensure hosts do not resolve to themselves via 127.0.0.1
  lineinfile:
    regexp: '^127\.0\.1\.1'
    line: ''
    path: /etc/hosts
  tags: hosts

- name: HOSTS. Ensure both hosts resolve to each other
  blockinfile:
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    dest: "/etc/hosts"
    backup: yes
  with_items:
    - {name: "{{primary_host}}", ip: "{{primary_rep_ip}}"}
    - {name: "{{secondary_host}}", ip: "{{secondary_rep_ip}}"}
    - {name: "{{primary_host_alt}}", ip: "{{primary_serv_ip}}"}
    - {name: "{{secondary_host_alt}}", ip: "{{secondary_serv_ip}}"}
  tags: hosts
