---
- hosts: nfsServers
  gather_facts: yes

  roles:
    - ../roles/hosts
    - ../roles/tools
    - ../roles/ansible-softwareraid
    - ../roles/drbd
    - ../roles/nfs
    - ../roles/ha
    # not needed finally, it was a matter of order of operations. - ../roles/cleanupandfix
    - ../roles/fio
    # # - ../roles/speedtestNfs
    - ../roles/goss

  # tasks:
    # - name: SpeedTest. Generate files on the nodes. OK TO FAIL.
    #   script: ../resources/scripts/filegenerator.sh
    #   tags: speedtest
    #   ## Use both nodes, fail at will.
    #   ## To use only primary, uncomment.
    #   # when: ansible_hostname == primary_host
    #   ignore_errors: yes


