---
- hosts: nfsServers
  gather_facts: yes

  tasks:
    - name: Generate files on the nodes. OK TO FAIL.
      script: ../resources/scripts/stressFileGenerator.sh
      ## Use both nodes, fail at will.
      ## To use only primary, uncomment.
      # when: ansible_hostname == primary_host
      ignore_errors: yes


